#!/bin/bash

# Script Name: /etc/hotplug.d/bakesale

# Main execution
[ "$ACTION" = "ifup" ] && /etc/init.d/bakesale enabled && \
logger -t bakesale -p "daemon.notice" "HOTPLUG TRIGGERED RELOAD" && \
/etc/init.d/bakesale reload || \
logger -t bakesale -p "daemon.err" "Exiting due to failed condition"

