#!/bin/bash /etc/rc.common

# Script: /etc/init.d/bakesale

START=21
USE_PROCD=1

BAKESALE_SERVICE_STATUS="/etc/init.d/bakesale"
BAKESALE_SCRIPT="/usr/lib/bakesale/bakesale.sh"

start_service() {
    "$BAKESALE_SCRIPT" start
}

reload_service() {
	"$BAKESALE_SERVICE_STATUS" status &>/dev/null || {
		echo "The bakesale service does not appear to be loaded."
		return 1
	}
    "$BAKESALE_SCRIPT" reload
}

stop_service() {
    "$BAKESALE_SCRIPT" stop
}

service_triggers() {
	procd_add_reload_trigger "firewall" "sqm" "bakesale"
}
