#!/bin/bash /etc/rc.common

# Script: /etc/init.d/bakesale

START=80
USE_PROCD=1

DSCP_SERVICE_STATUS="/etc/init.d/bakesale"
DSCP_SCRIPT="/usr/lib/bakesale/bakesale.sh"
AUTORATE_SCRIPT="/usr/lib/bakesale/autorate.sh"

start_service() {
    "$DSCP_SCRIPT" start

    autorate_instances=(/etc/bakesale.d/config.*.sh)

    for autorate_instance in "${!autorate_instances[@]}"
    do
        procd_open_instance "${autorate_instance}"
        procd_set_param command "$AUTORATE_SCRIPT" "${autorate_instances[autorate_instance]}"
        # uncomment if you want procd to restart your script if it terminated for whatever reason
        #procd_set_param respawn
        procd_close_instance
    done
}

reload_service() {
    "$DSCP_SERVICE_STATUS" status &>/dev/null || {
        echo "The bakesale service does not appear to be loaded."
        return 1
    }
    "$DSCP_SCRIPT" reload
}

stop_service() {
    "$DSCP_SCRIPT" stop
}

service_triggers() {
    procd_add_reload_trigger "firewall" "sqm" "bakesale"
}
