#!/bin/bash /etc/rc.common

# Script Name: /etc/init.d/bakesale

START=21  # Start priority
USE_PROCD=1  # Use process management daemon (Procd)
DEBUG=1  # Default to debugging mode

# Source helper scripts
. /usr/lib/bakesale/bakesale.sh

run_service() {
	local action="$1"
	local message="$2"

	if setup "$action"; then
		log notice "Service $message"
	else
		log error "Service $message failed"
		[ "$DEBUG" != 1 ] && {
			rm -f "/tmp/etc/bakesale-pre.include"
			rm -f "/tmp/etc/bakesale-post.include"
			nft delete table inet bakesale 2>/dev/null
		}
		return 1
	fi
}

start_service() {
	run_service start started
}

reload_service() {
	/etc/init.d/bakesale status &>/dev/null || {
		echo "The bakesale service does not appear to be loaded."
		return 1
	}

	run_service reload reloaded
}

stop_service() {
	rm -f "/tmp/etc/bakesale-pre.include"
	rm -f "/tmp/etc/bakesale-post.include"
	nft delete table inet bakesale 2>/dev/null
	log notice "Service stopped successfully"
}
