#!/bin/bash

# Get the list of IPs from the nftables set
IP_LIST=$(nft list set ip fw4 ips_blocklist_wan | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b")

for IP in $IP_LIST; do
    # Fetch RDAP data (using ARIN as an example, you might need other RDAP servers for non-ARIN IPs)
    CIDR=$(curl -s https://rdap.arin.net/registry/ip/$IP | jq -r '.startAddress + "-" + .endAddress')
    
    # Check if CIDR was successfully extracted
    if [[ ! -z $CIDR ]]; then
        nft add element ip fw4 ips_blacklist_net { $CIDR }
    fi
done
